entry_expire = 10

[database]
user= "leolee"
password = "password"
host = "localhost"
port = 5432
dbname = "lil-helper-db"
config = ""

[jwt.user]
realm = "lil-helper"
identity_key = "uid"
secret = "i am lil-helper secret 7768"
timeout = 60
max_refresh = 60