entry_expire = 10

[database]
  config = ""
  dbname = "lil-helper-db"
  host = "localhost"
  password = "password"
  port = 5432
  user = "leolee"

[jwt]

  [jwt.user]
    identity_key = "uid"
    max_refresh = 60
    realm = "lil-helper"
    secret = "i am lil-helper secret 7768"
    timeout = 60

[mission]
  levelsexp = [0,1,2,3,4,5,6,7,8,9]
  maxlevel = 10
  updateat = "00:00"

  [mission.totalweight]
    239A8B28B75D = [1,2,3]
    92578BAEB6EA = [1,2,3]
