// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/helpers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "list helpers",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "flag to query active user only (default: true)",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "flag to query all users (default: false)",
                        "name": "all",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apiModel.JsonObjectArray"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/helpers/{uid}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "ban helper",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/admin/mission": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "create mission",
                "parameters": [
                    {
                        "description": "set mission params",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apiModel.SetMissionParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/helpermodel.Mission"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/missions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "list missions by date(optional), else list today's missions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mission date from",
                        "name": "datefrom",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "mission date to",
                        "name": "dateto",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apiModel.JsonObjectArray"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/missions/{uid}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "update mission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mission uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "set mission params",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apiModel.SetMissionParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/helpermodel.Mission"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "delete mission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mission uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/admin/regist": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "user registration",
                "parameters": [
                    {
                        "description": "User registration parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apiModel.UserRegistParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/helperModel.PublicUser"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/screenshots": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "list screenshots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "screenshot date from",
                        "name": "datefrom",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "screenshot date to",
                        "name": "dateto",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if screenshot auditted (default: false)",
                        "name": "audit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apiModel.JsonObjectArray"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/screenshots/{uid}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "audit screenshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "screenshot uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "audit screenshot params",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apimodel.AuditScreenshotParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/helpermodel.Screenshot"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/base/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "user login parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apimodel.LoginParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apimodel.LoginResData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/base/refresh-token": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "User refresh token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apimodel.LoginResData"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/base/regist": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Base"
                ],
                "summary": "user registration",
                "parameters": [
                    {
                        "description": "User registration parameters",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apimodel.UserRegistParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/helpermodel.PublicUser"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/helper/mission": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Helper"
                ],
                "summary": "get mission",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/helpermodel.Mission"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/helper/screenshot": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Helper"
                ],
                "summary": "create screenshot",
                "parameters": [
                    {
                        "description": "set screenshot params",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apiModel.SetScreenshotParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/helpermodel.Screenshot"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/helper/screenshots": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Helper"
                ],
                "summary": "list screenshots by date(optional), else list today's screenshots",
                "parameters": [
                    {
                        "type": "string",
                        "description": "screenshot date from",
                        "name": "datefrom",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "screenshot date to",
                        "name": "dateto",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apiModel.JsonObjectArray"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/helper/screenshots/{uid}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Helper"
                ],
                "summary": "delete screenshot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "screenshot uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/helpers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "list top score users",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "top helpers limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apimodel.JsonObjectArray"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apiModel.JsonObjectArray": {
            "type": "object",
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "objects": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                }
            }
        },
        "apiModel.SetMissionParams": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "content": {
                    "type": "string",
                    "example": "this is a content"
                },
                "picture": {
                    "type": "string",
                    "example": "this/is/a/path/of/picture.jpg"
                },
                "score": {
                    "type": "integer"
                },
                "weight": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "apiModel.SetScreenshotParams": {
            "type": "object",
            "properties": {
                "missionUID": {
                    "type": "string",
                    "example": "screenshot_missionUID"
                },
                "picture": {
                    "type": "string",
                    "example": "this/is/a/path/of/picture.jpg"
                }
            }
        },
        "apiModel.UserRegistParam": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "my_password"
                },
                "username": {
                    "type": "string",
                    "example": "my_username"
                }
            }
        },
        "apimodel.AuditScreenshotParams": {
            "type": "object",
            "properties": {
                "approve": {
                    "type": "boolean"
                }
            }
        },
        "apimodel.JsonObjectArray": {
            "type": "object",
            "properties": {
                "keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "objects": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                }
            }
        },
        "apimodel.LoginParam": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "my_password"
                },
                "username": {
                    "type": "string",
                    "example": "my_username"
                }
            }
        },
        "apimodel.LoginResData": {
            "type": "object",
            "properties": {
                "expire": {
                    "type": "string",
                    "example": "2020-04-01T12:08:36+08:00"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsiOjE1ODU2nVpZCI6IVzZXJuYW1lIjoic3RyaW5nIn0.HbrhJbblrWLVqle6TI19bGX78ki4x5x1Wxs"
                }
            }
        },
        "apimodel.UserRegistParam": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "my_password"
                },
                "username": {
                    "type": "string",
                    "example": "my_username"
                }
            }
        },
        "handler.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "type": "object"
                },
                "msg": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "helperModel.PublicUser": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "admin": {
                    "type": "boolean"
                },
                "score": {
                    "type": "integer"
                },
                "userUID": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "helpermodel.Mission": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "content": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "uid": {
                    "type": "string"
                },
                "weight": {
                    "type": "string"
                }
            }
        },
        "helpermodel.PublicUser": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "admin": {
                    "type": "boolean"
                },
                "score": {
                    "type": "integer"
                },
                "userUID": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "helpermodel.Screenshot": {
            "type": "object",
            "properties": {
                "approve": {
                    "type": "boolean"
                },
                "audit": {
                    "type": "boolean"
                },
                "missionID": {
                    "type": "integer"
                },
                "picture": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.0.1",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "lil-helper swagger API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
